APP_PATH = $(CURDIR)
PICO_LIB_SDK_EXTRAS_PATH = ../../../picolibsdk-extras
#PICO_LIB_SDK_PATH = ${PICO_LIB_SDK_EXTRAS_PATH}/sdk/pico-lib-sdk
#PICO_SDK_PATH = ${PICO_LIB_SDK_EXTRAS_PATH}/sdk/pico-sdk

TARGET=TEMPLATE
DEVICE=picopad10
DEVCLASS=picopad

# ASM source files
ASRC +=

# C source files
CSRC +=

USE_WIFI = 0
USE_BTSTACK = 0
USE_TINYUSB = 0

# C++ source files
SRC += src/main.cpp

# Makefile includes
include ${PICO_LIB_SDK_EXTRAS_PATH}/build/_makefile.inc
include ${PICO_LIB_SDK_EXTRAS_PATH}/build/Makefile.inc
