APP_PATH = $(CURDIR)
PICO_LIB_SDK_EXTRAS_PATH = ../picolibsdk-extras
PICO_LIB_SDK_EXTRAS_PATH = ../../../picolibsdk-extras
#PICO_LIB_SDK_PATH = ${PICO_LIB_SDK_EXTRAS_PATH}/sdk/pico-lib-sdk
#PICO_SDK_PATH = ${PICO_LIB_SDK_EXTRAS_PATH}/sdk/pico-sdk

TARGET=HSTXDVI
DEVICE=pico2
DEVCLASS=pico
BOARD=pimoroni_pico_plus2

# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC +=

CSRC += src/main.c

# Makefile includes
include ${PICO_LIB_SDK_EXTRAS_PATH}/build/_makefile.inc
include ${PICO_LIB_SDK_EXTRAS_PATH}/build/Makefile.inc
